default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: video-upload-example_development

test:
  <<: *default
  database: video-upload-example_test

production:
  <<: *default
  database: video-upload-example_production
  username: forest
  password: <%= ENV['VIDEO_UPLOAD_EXAMPLE_DATABASE_PASSWORD'] %>
